import About from "@/components/About";
import Contact from "@/components/Contact";
import Funding from "@/components/Funding";
import Hero from "@/components/Hero";
import People from "@/components/People";
import { Inter } from "@next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Pnoi</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero
				heading="Pnoi-phone"
				message="A biomedical device for detecting and monitoring asthma using breath sounds"
			/>
			{/* <Slider slides={slides} /> */}
			<About />
			<Funding />
			<People />
			<Contact />
		</>
	);
}
