import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Hero from "@/components/Hero";
import Slider from "@/components/Slider";
import { slides } from "@/data/slides";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Pnoi</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero
				heading="Breathe In, Breathe Out"
				message="Easing diagnosis and monitoring of Asthma with sounds of breath."
			/>
			<Slider slides={slides} />
		</>
	);
}
